
export const QR_MERCHANT_SPECS = [
  { id: 'qr_starbucks_raffles', merchant: 'Starbucks Raffles Place', amount: 8.5, category: 'Coffee', location: 'Raffles Place', tags: ['drink_coffee'] },
  { id: 'qr_starbucks_one', merchant: 'Starbucks One Raffles', amount: 9.2, category: 'Coffee', location: 'One Raffles Place', tags: ['drink_coffee'] },
  { id: 'qr_li_ho', merchant: 'LiHO Tea', amount: 6.8, category: 'Drinks', location: 'Orchard Road', tags: ['drink_bubble_tea'] },
  { id: 'qr_gong_cha', merchant: 'Gong Cha', amount: 7.5, category: 'Drinks', location: 'Jurong Point', tags: ['drink_bubble_tea'] },
  { id: 'qr_mr_bean', merchant: 'Mr Bean', amount: 4.5, category: 'Drinks', location: 'Tampines Mall', tags: ['drink_soy'] },
  { id: 'qr_boost', merchant: 'Boost Juice', amount: 8.9, category: 'Drinks', location: 'VivoCity', tags: ['drink_juice'] },
  { id: 'qr_ichiban_sushi', merchant: 'Ichiban Sushi', amount: 38.5, category: 'Dining', location: 'Orchard Road', tags: ['food_casual'] },
  { id: 'qr_pizza_hut', merchant: 'Pizza Hut', amount: 26.4, category: 'Dining', location: 'Thomson Road', tags: ['food_casual'] },
  { id: 'qr_ya_kun', merchant: 'Ya Kun Kaya Toast', amount: 7.2, category: 'Dining', location: 'Orchard Road', tags: ['food_hawker', 'drink_milo'] },
  { id: 'qr_din_tai_fung', merchant: 'Din Tai Fung', amount: 42.8, category: 'Dining', location: 'Orchard Road', tags: ['food_casual'] },
  { id: 'qr_killiney', merchant: 'Killiney Kopitiam', amount: 6.5, category: 'Dining', location: 'Killiney Road', tags: ['food_hawker', 'drink_milo'] },
  { id: 'qr_marina_hawker', merchant: 'Marina Bay Hawker', amount: 9.8, category: 'Dining', location: 'Marina Bay', tags: ['food_hawker'] },
  { id: 'qr_toast_box', merchant: 'Toast Box', amount: 6.5, category: 'Dining', location: 'ION Orchard', tags: ['food_hawker', 'drink_coffee'] },
  { id: 'qr_dough_culture', merchant: 'Dough Culture', amount: 12.8, category: 'Dining', location: 'North Bridge Road', tags: ['food_casual'] },
  { id: 'qr_uniqlo_orchard', merchant: 'Uniqlo Orchard', amount: 45.9, category: 'Retail', location: 'Orchard Road', tags: ['retail_fashion'] },
  { id: 'qr_hm_vivo', merchant: 'H&M VivoCity', amount: 38.2, category: 'Retail', location: 'VivoCity', tags: ['retail_fashion'] },
  { id: 'qr_muji', merchant: 'Muji Orchard', amount: 34.5, category: 'Retail', location: 'Orchard Road', tags: ['retail_fashion', 'retail_home'] },
  { id: 'qr_cotton_on', merchant: 'Cotton On', amount: 29.9, category: 'Retail', location: 'Bugis Junction', tags: ['retail_fashion'] },
  { id: 'qr_decathlon', merchant: 'Decathlon Singapore', amount: 59.9, category: 'Retail', location: 'Bedok', tags: ['retail_sports'] },
  { id: 'qr_guardian', merchant: 'Guardian Pharmacy', amount: 18.5, category: 'Retail', location: 'Orchard Road', tags: ['retail_pharmacy'] },
  { id: 'qr_watsons', merchant: 'Watsons', amount: 15.9, category: 'Retail', location: 'Tampines Mall', tags: ['retail_pharmacy'] },
  { id: 'qr_changi_dutyfree', merchant: 'Changi Airport Duty Free', amount: 68, category: 'Retail', location: 'Changi Airport T1', tags: ['retail_dutyfree'] },
  { id: 'qr_cold_storage', merchant: 'Cold Storage', amount: 34.8, category: 'Groceries', location: 'Orchard Road', tags: ['groceries'] },
  { id: 'qr_ntuc_fairprice', merchant: 'NTUC FairPrice', amount: 18.6, category: 'Groceries', location: 'Marina Bay', tags: ['groceries'] },
  { id: 'qr_finest', merchant: 'FairPrice Finest', amount: 52.3, category: 'Groceries', location: 'Scotts Square', tags: ['groceries'] },
  { id: 'qr_bengawan_solo', merchant: 'Bengawan Solo', amount: 22.5, category: 'Retail', location: 'Marina Square', tags: ['retail_bakery'] },
  { id: 'qr_scoot', merchant: 'Scoot', amount: 165, category: 'Travel', location: 'Changi Airport', tags: ['travel_flight'] },
  { id: 'qr_airasia', merchant: 'AirAsia', amount: 189, category: 'Travel', location: 'Changi Airport', tags: ['travel_flight'] },
  { id: 'qr_agoda', merchant: 'Agoda', amount: 145, category: 'Travel', location: 'Online', tags: ['travel_hotel'] },
  { id: 'qr_booking', merchant: 'Booking.com', amount: 210, category: 'Travel', location: 'Online', tags: ['travel_hotel'] },
  { id: 'qr_klook', merchant: 'Klook', amount: 56, category: 'Travel', location: 'Online', tags: ['travel_activity'] },
];

export function toQrMerchantRecord(spec) {
  return {
    id: spec.id,
    merchant: spec.merchant,
    amount: spec.amount,
    category: spec.category,
    location: spec.location,
    tags: spec.tags || [],
    filename: `${spec.id}.png`,
    imageUrl: `assets/demo-qr/${spec.id}.png`,
    payload: JSON.stringify({
      type: 'nets_pay',
      id: spec.id,
      merchant: spec.merchant,
      amount: spec.amount,
      category: spec.category,
    }),
  };
}
